### ISSUE TITLE
Problems importing

### ISSUE THREAD

**Issue by pepa65** [rwynn/llave#5]
Trying to import a KeePass 1.X XML database, not sure why it doesn't work.
![llave-error](https://user-images.githubusercontent.com/6505000/53157781-1dde5080-3577-11e9-87e3-5f80b3a754df.png)

If I convert the xml to ironclad json, the import works with the same data.

**Comment by rwynn** [comment]
It appears that the asynchronous unlink function now requires a 2nd argument.

**Comment by pepa65** [comment]
Now it says it has imported all entries, but it actually doesn't display any... The json import still works as before.

(Very cool to have change-password and clipboard-timeout implemented though!!)

**Comment by rwynn** [comment]
That’s weird. It was working for me with the example XML and Csv from the KeePass site.

https://keepass.info/help/base/importexport.html

Only 1.x formats tried (as that is all that is supported).

**Comment by rwynn** [comment]
I also tried the generic import with the KeePass sample CSV.

**Comment by rwynn** [comment]
Is it possible you might be able to attach a sample XML (with fake data of course) that you are able to recreate the issue with?   I just tried again with the sample 1.X from KeePass...

```
<?xml version="1.0" encoding="UTF-8"?>
<pwlist>
<pwentry>
	<group>General</group>
	<title>Sample Entry</title>
	<username>Greg</username>
	<url>http://www.web.com</url>
	<password>sVoVd2HohmC7hpKYV5Bs</password>
	<notes>This entry is stored in the &#39;General&#39; group.</notes>
	<uuid>4d9a9420ac7c4a8ae688762eac8871a9</uuid>
	<image>0</image>
	<creationtime>2006-12-31T11:52:01</creationtime>
	<lastmodtime>2006-12-31T11:52:01</lastmodtime>
	<lastaccesstime>2006-12-31T11:52:01</lastaccesstime>
	<expiretime expires="false">2999-12-28T23:59:59</expiretime>
</pwentry>
<pwentry>
	<group tree="General">Windows</group>
	<title>Sample Entry #2</title>
...
```

And could view the entries after the import.

**Comment by pepa65** [comment]
The Sample.xml works here too. The difference that I can see between what KeePassX exports on my machine compared to the sample is, that the sample has \x0d0a (CRLF) line endings while mine has only LF, and the Sample starts with \xefbbbf (BOM) before the xml starts.

Oh, my xml looks completely different...
```
<!DOCTYPE KEEPASSX_DATABASE>
<database>
 <group>
  <title>login</title>
  <icon>0</icon>
  <entry>
```
Etc.

Is it possible that the keepass.info site is misstaken? I think the sample file is the xml export from Keepass 2.X perhaps??

**Comment by rwynn** [comment]
That’s possible. I don’t actually use KeePass so I don’t know. I did the coding based on the existence of those samples under the 1.X label.

**Comment by pepa65** [comment]
KeePassX is getting long in the tooth and is no longer maintained, so I want to make sure I have at least 2 feasible longer-term alternatives with both CLI and GUI interfaces. Ironclad/llave is one of those. :-)
As I said, I have a script that can convert PassKeeperX's "xml" to ironclad json, so I'm OK, it would just be cool if that was not needed, but not a huge priority.
(My other alternative is pwsafe, but the Linux client is the red-haired stepchild, and import there is byzantine...)

**Comment by pepa65** [comment]
I checked out keepass2, and it has a yet different xml format. But I also found out that KeepassX has a separate xml format, that is obviously not supported by ironclad. I'm afraid this Issue is invalid as a bug report -- well, at least the error message got fixed, and the Keepass 1.X xml is now importable.

**Comment by rwynn** [comment]
I will need to add support for those 2 formats. Ironclad only supports import of its own json. So llave does conversions for xml and Csv.

**Comment by pepa65** [comment]
This is a versatile general resource: https://gitlab.com/roddhjav/pass-import
I usually like perl sources, because they are often well done and well documented. Like here: http://kpcli.sourceforge.net/
